version: '3.9'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    ports:
      - "443:443"
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: ${TS_HOSTNAME}
    volumes:
      - /dev/net/tun:/dev/net/tun
      - nginx-tailscale:/var/lib/tailscale
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl
      - shared-data:/usr/share/nginx/html:ro

  app:
    build: ./app
    container_name: app
    environment:
      GIT_REPO: ${GIT_REPO}
      GIT_BRANCH: ${GIT_BRANCH}
      AUTO_CLONE: "true"
      COOKIE_PATH: ${COOKIE_PATH}
    volumes:
      - ./files:/app/files:ro
      - app-code:/app/code
      - app-config:/app/config
      - app-extensions:/app/extensions
      - shared-data:/share/data

    rclone-backup:
    build:
      context: ./rclone
    container_name: rclone-backup
    depends_on:
      - app
    environment:
      WEBDAV_URL:      ${WEBDAV_URL}
      WEBDAV_PATH:     ${WEBDAV_PATH}
      WEBDAV_USER:     ${WEBDAV_USER}
      WEBDAV_PASS_ENC: ${WEBDAV_PASS_ENC}
      WEBDAV_VENDOR:   ${WEBDAV_VENDOR}
      WEBDAV_REMOTE_NAME: ${WEBDAV_REMOTE_NAME}
    entrypoint: ["/bin/sh", "/config/backup.sh"]
    volumes:
      - shared-data:/share/data
      - ./rclone:/config:ro


volumes:
  nginx-tailscale:
  app-code:
  app-config:
  app-extensions:
  shared-data: